export const GET_ALL_INGRIDIENTS = 'GET_ALL_INGRIDIENTS'
export const ADD_ONE_INGRIDIENT = 'ADD_ONE_INGRIDIENT'
export const DELETE_ONE_INGRIDIENT = 'DELETE_ONE_INGRIDIENT'
export const ADD_ONE_STEP = 'ADD_ONE_STEP'
export const DELETE_ONE_STEP = 'DELETE_ONE_STEP'
export const ADD_PHOTO_STEP = "ADD_PHOTO_STEP"
