export const GET_MY_RECIPES = 'GET_MY_RECIPES';
export const DELETE_MY_RECIPE = 'DELETE_MY_RECIPE'
export const ERROR_MASSAGE_POST_RECIPE = 'ERROR_MASSAGE_POST_RECIPE'
export const DELETE_ERROR_MASSEGE = 'DELETE_ERROR_MASSEGE'
export const ADD_RECIPE = 'ADD_RECIPE'
