export const GET_MY_RECIPE = 'GET_MY_RECIPE';
export const DELETE_MY_RECIPE = 'DELETE_MY_RECIPE'
export const PUBLISH_MY_RECIPE = 'PUBLISH_MY_RECIPE'
export const GET_STATUS_PUBLISH_RECIPE = 'GET_STATUS_PUBLISH_RECIPE'
